### ISSUE TITLE
Missing Descriptions for Spell and Trap Cards

### ISSUE THREAD

**Issue by cntrl-alt-lenny** [Pietracoops/yugioh_cardlist_scraper#6]
The CSV files generated for the sets do not include descriptions for any of the spell or trap cards, whereas the monster cards have descriptions as expected.

**Steps to Reproduce:**
_1. I cloned the repository and ran the script using the 'fast' option as instructed in the README.
2. After the script completed, I downloaded the CSV files and opened them in Excel.
3. Upon reviewing the files, I noticed that spell and trap cards lack description text._

I am not sure if this is a scraping issue or if the data is not available from the source. Could you please look into this?

Thank you for your time and assistance!

**Comment by Pietracoops** [comment]
I will look into this, thanks for bringing this up!

**Comment by Pietracoops** [comment]
It seems that this is an issue with the python version. I am able to replicate this issue with a later version of python (e.g. 3.10.6) but I do not have this issue with python 3.8.10. As a workaround, please try it with that version, can download it [here](https://www.python.org/downloads/release/python-3810/)

**Comment by Pietracoops** [comment]
closing this issue
