### ISSUE TITLE
Cannot run the main.py

### ISSUE THREAD

**Issue by MathiasPMC** [Pietracoops/yugioh_cardlist_scraper#7]
Hello, I'm not much of a programmer so sorry if it's just a skill issue, I tried to follow the readme but main.py was instantaneously shutting down so I used Pycharm to run main.py (I installed the package beforehand using the terminal) but I have this error that I cannot understand because of my poor python knowledge : 

Traceback (most recent call last):
  File "C:\Users\Mathias\Documents\yugioh_cardlist_scraper-main\venv\lib\site-packages\git\__init__.py", line 89, in <module>
    refresh()
  File "C:\Users\Mathias\Documents\yugioh_cardlist_scraper-main\venv\lib\site-packages\git\__init__.py", line 76, in refresh
    if not Git.refresh(path=path):
  File "C:\Users\Mathias\Documents\yugioh_cardlist_scraper-main\venv\lib\site-packages\git\cmd.py", line 392, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Mathias\Documents\yugioh_cardlist_scraper-main\main.py", line 6, in <module>
    import helpers
  File "C:\Users\Mathias\Documents\yugioh_cardlist_scraper-main\helpers.py", line 3, in <module>
    import git
  File "C:\Users\Mathias\Documents\yugioh_cardlist_scraper-main\venv\lib\site-packages\git\__init__.py", line 91, in <module>
    raise ImportError("Failed to initialize: {0}".format(_exc)) from _exc
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

I did use python 3.8.10.

Thank you for your consideration.

**Comment by MathiasPMC** [comment]
Ok I manage to fix the issue by installing GIT and following this instructions : 
https://stackoverflow.com/questions/48399498/git-executable-not-found-in-python

**Comment by MathiasPMC** [comment]
I'm sorry to reopen this but now, when run main.py I do get csv files but they are all filled with just one line : 
Passcode$Name$Status$Attribute$type$link$link_arrows$rank$pendulum_scale$level$attack$defense$spell_attribute$summoning_condition$pendulum_condition$card_text$card_supports$card_anti_supports$card_actions$effect_types$

I assume the program isn't looping into each card and getting the informations but I don't know why and I don't have any error log to provide. Would you have any idea what could cause that ?

**Comment by Pietracoops** [comment]
~~Would you be able to give me more information about your setup? Any information you can provide helps~~
Seems like there is a problem with the script - I will investigate and be back

**Comment by Pietracoops** [comment]
Thanks for posting this find. The website where we scrape the cards performed an update that broke the script. I have fixed it now. Perform a pull on the main branch - should be working again. If there are other issues create a new issue.
